[package]
build = "build/main.rs"
name = "rb-sys"
version = "0.9.65"
edition = "2018"
readme = "readme.md"
categories = ["external-ffi-bindings"]
description = "Rust bindings for the CRuby API"
documentation = "https://docs.rs/rb-sys"
homepage = "https://github.com/oxidize-rb/rb-sys"
license = "MIT OR Apache-2.0"
links = "rb"
repository = "https://github.com/oxidize-rb/rb-sys"
rust-version = "1.60"

[build-dependencies]
rb-sys-local = { version = "0.9.65", path = "../rb-sys-local", optional = true }

[features]
default = ["local"]
local = ["rb-sys-local"]
link-ruby = ["rb-sys-local?/link-ruby"]
no-link-ruby = ["rb-sys-local?/no-link-ruby"]
ruby-macros = ["rb-sys-local?/ruby-macros"]
ruby-static = ["rb-sys-local?/ruby-static"]
global-allocator = ["rb-sys-local?/global-allocator"]
docs = ["rb-sys-local?/docs"]
bindgen-rbimpls = ["rb-sys-local?/bindgen-rbimpls"]
bindgen-deprecated-types = ["rb-sys-local?/bindgen-deprecated-types"]
bindgen-layout-tests = ["rb-sys-local?/bindgen-layout-tests"]
bindgen-impl-debug = ["rb-sys-local?/bindgen-impl-debug"]

[lib]
doctest = false
