name: Cache Clean

on:
  workflow_dispatch:
    inputs:
      all-branches:
        type: boolean
        description: "Delete caches for all branches (nuclear option)"
  pull_request:
    types:
      - closed

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete caches
        uses: actions/github-script@v6
        with:
          script: |
            let totalDeleted = 0;
            let totalBytes = 0;
            let pageSize = 10;
            let inputs = context.payload.inputs;
            let ref = context.ref;

            if (inputs && inputs["all-branches"] == "true") {
              console.warn("Deleting caches for all branches");
              ref = undefined;
            }

            async function fetchCaches(params) {
              return github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ...params
              });
            }

            async function deleteCachesForRef(ref) {
              let currentPage = 1;
              let currentCaches = await fetchCaches({ per_page: pageSize, page: currentPage, ref: ref });
              let totalCount = currentCaches.data.total_count;

              console.log(`Found ${totalCount} caches for ref ${ref}`);

              while (true) {
                let promises = [];

                for (const cache of currentCaches.data.actions_caches) {
                  const deleted = github.rest.actions.deleteActionsCacheById({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    cache_id: cache.id,
                  });

                  deleted.then(() => {
                    let mb = cache.size_in_bytes / 1024 / 1024;
                    console.log(
                      `Deleted cache ${cache.id} (size: ${mb}MB, ref: ${ref}, page: ${currentPage})`
                    );
                    totalDeleted++;
                    totalBytes += cache.size_in_bytes;
                  });

                  promises.push(deleted);
                }

                await Promise.all(promises);

                if (totalDeleted >= totalCount) {
                  console.log(`Break at page ${currentPage} (total: ${totalCount}, pageSize: ${pageSize})`);
                  break;
                } else {
                  currentPage++;
                  currentCaches = await fetchCaches({ per_page: pageSize, page: currentPage, ref: ref });
                }
              }
            }

            await deleteCachesForRef(ref);
            let totalMb = totalBytes / 1024 / 1024;
            console.log(`Clear completed, deleted ${totalDeleted} caches (${totalMb} MB)`);
