name: Cache Clean

on:
  workflow_dispatch:
    inputs:
      all-branches:
        type: boolean
        description: "Delete caches for all branches (nuclear option)"
  pull_request:
    types:
      - closed

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete caches
        uses: actions/github-script@v6
        with:
          script: |
            let currentPage = 1
            let totalDeleted = 0

            const ref = core.getBooleanInput('all-branches') ? undefined : context.ref

            while (true) {
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page: currentPage,
                ref: ref,
                page: currentPage,
              })

              for (const cache of caches.data.actions_caches) {
                const deleted = await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })

                console.log(`Deleted cache ${cache.key} (id: ${cache.id}) on page ${currentPage})`)
                totalDeleted++
              }

              if (caches.data.total_count <= currentPage * 100) {
                console.log(`No more caches to delete on page ${currentPage}, total count: ${caches.data.total_count}`)
                break
              }

              currentPage++
            }

            console.log(`Clear completed, deleted ${totalDeleted} caches`)
