---
name: Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      # This compiles for all supported Ruby cross-compilation platforms.
      - id: fetch
        uses: oxidize-rb/actions/fetch-ci-data@main
        with:
          supported-ruby-platforms: |
            exclude: []

  cross-gem:
    name: Cross compile test
    needs: ci-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: oxidize-rb/oxi-test
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: ✏️ Replace rb-sys
        shell: bash
        run: |
          mkdir -p .cargo
          echo >> .cargo/config.toml
          echo "[patch.crates-io]" >> .cargo/config.toml
          echo "rb-sys = { git = \"https://github.com/oxidize-rb/rb-sys\", ref = \"${{ github.ref }}\" }" >> .cargo/config.toml
          echo "rb-sys-env = { git = \"https://github.com/oxidize-rb/rb-sys\", ref = \"${{ github.ref }}\" }" >> .cargo/config.toml
          echo "rb-sys-build = { git = \"https://github.com/oxidize-rb/rb-sys\", ref = \"${{ github.ref }}\" }" >> .cargo/config.toml
          cargo update -p rb-sys
          cargo update -p rb-sys-env
          cargo update -p rb-sys-build
          ruby -e "File.write('Gemfile', File.read('Gemfile').gsub(/gem .rb_sys.*$/, 'gem \"rb_sys\", github: \"oxidize-rb/rb-sys\", ref: \"${{ github.ref }}\"'))" || true
          bundle install -j3 --retry 3 || true
      - uses: oxidize-rb/actions/cross-gem@v1
        with:
          platform: ${{ matrix.ruby-platform }}
          ruby-versions: "2.6, 2.7, 3.0, 3.1, 3.2"
      - uses: actions/upload-artifact@v3
        with:
          name: cross-gem-${{ matrix.ruby-platform }}
          path: pkg/*-${{ matrix.ruby-platform }}.gem
          if-no-files-found: error
          retention-days: 1

  test:
    name: ${{ matrix.repo.slug }} (ruby=${{ matrix.ruby }}, os=${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        repo:
          - name: "oxidize-rb/oxi-test"
            slug: oxi-test
            ref: main
            run: bundle exec rake
          - name: "bytecodealliance/wasmtime-rb"
            slug: wasmtime
            ref: main
            run: bundle exec rake
          - name: "matsadler/magnus"
            slug: magnus
            ref: main
            run: cargo test
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        rust: ["stable"]
        ruby: ["2.7", "3.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log matrix
        shell: bash
        env:
          INPUTS: ${{ toJSON(matrix) }}
        run: |
          echo "$INPUTS" | jq
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.name }}
          ref: ${{ matrix.repo.ref }}
      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        id: setup
        with:
          ruby-version: ${{ matrix.ruby }}
          rustup-toolchain: ${{ matrix.rust }}
          cargo-cache: true
      - name: ✏️ Replace rb-sys
        shell: bash
        run: |
          mkdir -p .cargo
          echo >> .cargo/config.toml
          echo "[patch.crates-io]" >> .cargo/config.toml
          echo "rb-sys = { git = \"https://github.com/oxidize-rb/rb-sys\", ref = \"${{ github.ref }}\" }" >> .cargo/config.toml
          echo "rb-sys-env = { git = \"https://github.com/oxidize-rb/rb-sys\", ref = \"${{ github.ref }}\" }" >> .cargo/config.toml
          echo "rb-sys-build = { git = \"https://github.com/oxidize-rb/rb-sys\", ref = \"${{ github.ref }}\" }" >> .cargo/config.toml
          cargo update -p rb-sys
          cargo update -p rb-sys-env
          cargo update -p rb-sys-build
          ruby -e "File.write('Gemfile', File.read('Gemfile').gsub(/gem .rb_sys.*$/, 'gem \"rb_sys\", github: \"oxidize-rb/rb-sys\", ref: \"${{ github.ref }}\"'))" || true
          bundle install -j3 --retry 3 || true
          bundle update rb_sys || true
      - name: 🧪 Run tests for ${{ matrix.repo.slug }}
        shell: bash
        run: ${{ matrix.repo.run }}
